### ISSUE TITLE
Ion (and Hybrid) Engines confuse Engineer

### ISSUE THREAD

**Issue by Kiithnaras** [CYBUTEK/Engineer#4]
Attempting to use any sort of Xenon-powered engine (Ions, both vanilla and custom, as well as Ion Hybrids) with Engineer fails to even register as a valid engine or thruster. It is treated as having no Delta-V at all. Will test with the KSP Interstellar plasma/thermal engines.

**Comment by Kiithnaras** [comment]
KSPI's Thermal and Plasma engines appear to work fine. Then again, the plasma engines take KSPI's MegaJoules for energy, whilst stock and custom Ion/Hybrid engines use vanilla ElectricCharge. Something fishy going on here.

**Comment by CYBUTEK** [comment]
Try using https://github.com/Gerry1135/Engineer which is the current most up-to date version of Engineer.  That fork is set to be pulled and merged with this one in the near future.

**Comment by emlun** [comment]
Unrelated to this particular issue thread, but the issue was brought up... Which repo is the master one (i.e. the one I should send bug reports to)?

**Comment by CYBUTEK** [comment]
For the time being, issue your bugs relating to simulation mechanics to https://github.com/Gerry1135/Engineer.  Once the new simulation code is complete, it will then get merged and this will become the master again.  Whilst this issue remains open, consider the other repo the master.

**Comment by emlun** [comment]
I can confirm that using Gerry's latest version solves this problem for me.
